general {
    hide_cursor = true
}
background {
    monitor =
    color = rgba(19221eff)
}
label {
    monitor =
    text = $TIME
    color = rgba(a7c080ff)
    font_size = 72
    font_family = DejaVu Sans Mono
    position = 0, 140
    halign = center
    valign = center
}
label {
    monitor =
    text = $USER
    color = rgba(d3c6aaff)
    font_size = 18
    font_family = DejaVu Sans Mono
    position = 0, 50
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    inner_color = rgba(2d3932ff)
    outer_color = rgba(a7c080ff)
    check_color = rgba(7fbbb3ff)
    fail_color = rgba(e67e80ff)
    font_color = rgba(d3c6aaff)
    font_family = DejaVu Sans Mono
    placeholder_text = Password
    fail_text = $PAMFAIL
    fade_on_empty = false
    rounding = 12
    position = 0, -35
    halign = center
    valign = center
}
