font=DejaVu Sans Mono 11
background-color=#202824f5
text-color=#d3c6aa
border-color=#a7c080
border-size=2
border-radius=12
padding=16
margin=12
width=340
height=160
default-timeout=6000
anchor=top-right
[urgency=critical]
border-color=#e67e80
default-timeout=0
